#Seatwork 6.1 Exploratory Data Analysis on Your Own Dataset
 CPE311 Computational Thinking with Python

Name: Dela Cruz, Eugene

Section: CPE22S3

Performed on: 03/11/2024

Submitted on: 03/11/2024

Submitted to: Engr. Roman M. Richard

In [ ]:
filepath = '/content/LeaguePlayerStats.csv'
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv(filepath)

In [ ]:
data

,summonerName,summonerLevel,rank,wins,losses,winRate,kills,deaths,assists,prefLane,...,minionsKilled,goldEarned,turretTakedowns,visionScore,dragonKills,longestTimeSpentLiving,totalDamageDealt,totalDamageTaken,gameDuration,gameStart
0,RoséPosié,712,BRONZE,13,12,0.52,3.20,6.72,15.36,SUPPORT,...,50.32,8982.20,1,45.56,0,506.96,48651.12,544240,28.566667,7.216000
1,Xest,199,BRONZE,12,13,0.48,8.36,5.72,14.44,SUPPORT,...,47.40,11866.56,0,29.96,0,494.00,78143.68,441284,24.580667,16.400000
2,SilverHawk0,340,BRONZE,11,14,0.44,8.20,9.00,7.88,TOP,...,186.16,13236.60,1,19.96,0,438.64,150665.56,743065,30.250667,16.724667
3,Res93,61,BRONZE,12,13,0.48,8.60,7.52,8.20,ADC,...,190.00,13367.08,2,25.36,0,558.36,170517.52,594545,30.931333,17.265333
4,B3tterTh4nYo0,124,BRONZE,8,17,0.32,5.24,7.32,8.76,JUNGLE,...,97.76,11655.24,0,21.28,0,563.40,152541.04,652545,29.800000,13.505333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2280,DarkLady Lilith,516,SILVER,12,13,0.48,7.36,6.04,12.92,MIDDLE,...,138.36,12483.88,2,36.24,0,634.64,124161.88,540583,31.024000,15.213333
2281,IceTeaTs,241,SILVER,9,16,0.36,7.40,7.96,11.68,NONE,...,98.52,12285.04,1,9.44,0,346.32,97369.36,521546,22.320000,14.589333
2282,EasyEichel,312,SILVER,15,10,0.60,9.20,8.04,8.36,MIDDLE,...,87.72,13425.88,1,14.48,0,374.04,196456.52,809734,28.762667,15.082667
2283,popomu elleyin,520,SILVER,9,16,0.36,6.36,7.76,7.92,NONE,...,103.88,14513.68,1,24.40,0,404.08,143844.24,826660,29.032000,14.207333
2284,yELFD,242,SILVER,14,11,0.56,5.16,6.28,7.76,TOP,...,145.08,11735.84,2,13.60,0,523.24,138998.40,699002,28.106667,11.912000

In [ ]:
data.columns

Index(['summonerName', 'summonerLevel', 'rank', 'wins', 'losses', 'winRate',
       'kills', 'deaths', 'assists', 'prefLane', 'campsKilled',
       'minionsKilled', 'goldEarned', 'turretTakedowns', 'visionScore',
       'dragonKills', 'longestTimeSpentLiving', 'totalDamageDealt',
       'totalDamageTaken', 'gameDuration', 'gameStart'],
      dtype='object')

In [ ]:
data.dtypes

summonerName               object
summonerLevel               int64
rank                       object
wins                        int64
losses                      int64
winRate                   float64
kills                     float64
deaths                    float64
assists                   float64
prefLane                   object
campsKilled               float64
minionsKilled             float64
goldEarned                float64
turretTakedowns             int64
visionScore               float64
dragonKills                 int64
longestTimeSpentLiving    float64
totalDamageDealt          float64
totalDamageTaken            int64
gameDuration              float64
gameStart                 float64
dtype: object

In [ ]:
# Display the total number of records
num_record = len(data)
print("Total number of records: ", num_record)

Total number of records:  2285

In [ ]:
#  Display the first 20 records
data[0:20]

,summonerName,summonerLevel,rank,wins,losses,winRate,kills,deaths,assists,prefLane,...,minionsKilled,goldEarned,turretTakedowns,visionScore,dragonKills,longestTimeSpentLiving,totalDamageDealt,totalDamageTaken,gameDuration,gameStart
0,RoséPosié,712,BRONZE,13,12,0.520000,3.200000,6.720000,15.360000,SUPPORT,...,50.320000,8982.200000,1,45.560000,0,506.960000,48651.120000,544240,28.566667,7.216000
1,Xest,199,BRONZE,12,13,0.480000,8.360000,5.720000,14.440000,SUPPORT,...,47.400000,11866.560000,0,29.960000,0,494.000000,78143.680000,441284,24.580667,16.400000
2,SilverHawk0,340,BRONZE,11,14,0.440000,8.200000,9.000000,7.880000,TOP,...,186.160000,13236.600000,1,19.960000,0,438.640000,150665.560000,743065,30.250667,16.724667
3,Res93,61,BRONZE,12,13,0.480000,8.600000,7.520000,8.200000,ADC,...,190.000000,13367.080000,2,25.360000,0,558.360000,170517.520000,594545,30.931333,17.265333
4,B3tterTh4nYo0,124,BRONZE,8,17,0.320000,5.240000,7.320000,8.760000,JUNGLE,...,97.760000,11655.240000,0,21.280000,0,563.400000,152541.040000,652545,29.800000,13.505333
5,cndyksh,463,BRONZE,16,9,0.640000,8.440000,6.960000,6.440000,TOP,...,136.440000,12595.800000,2,16.280000,0,490.440000,122873.720000,839827,28.432667,17.368000
6,LeMMe THink,508,BRONZE,14,11,0.560000,6.000000,7.120000,6.000000,NONE,...,69.560000,13705.040000,1,10.880000,0,309.280000,115038.640000,741382,23.239333,18.082667
7,DawnOfWarr,642,BRONZE,11,14,0.440000,10.040000,8.400000,8.680000,MIDDLE,...,135.440000,13852.640000,1,14.200000,0,511.120000,151318.880000,743666,30.590667,16.532000
8,Someone creepy,139,BRONZE,12,13,0.480000,7.960000,11.760000,18.560000,NONE,...,68.600000,12101.400000,1,6.480000,0,256.840000,73314.040000,732080,22.040667,16.800000
9,Avalanche2510,488,BRONZE,10,15,0.400000,4.960000,8.200000,9.360000,ADC,...,161.760000,11517.280000,2,21.120000,0,571.400000,135141.560000,578895,31.280000,19.454000
10,Fran1kenStein,316,BRONZE,15,10,0.600000,4.280000,7.280000,12.640000,SUPPORT,...,120.200000,11343.760000,1,37.720000,0,648.400000,102434.120000,659661,32.490000,16.385333
11,Hide The Memes,30,BRONZE,7,2,0.777778,10.888889,6.111111,11.111111,MIDDLE,...,176.666667,15715.555556,3,18.222222,0,664.555556,207158.333333,260929,32.412963,18.148148
12,xfili02,337,BRONZE,10,15,0.400000,6.080000,7.000000,9.920000,TOP,...,171.920000,12873.360000,1,15.440000,0,554.400000,171467.200000,722526,28.469333,18.442667
13,Pok1 Feet,323,BRONZE,12,13,0.480000,6.920000,5.560000,5.080000,MIDDLE,...,180.480000,11631.560000,0,17.200000,0,608.920000,140302.320000,558984,27.981333,17.744667
14,didacfaker,406,BRONZE,11,14,0.440000,7.640000,7.200000,6.520000,ADC,...,209.840000,14016.320000,2,21.280000,0,586.920000,181596.120000,642326,32.099333,12.637333
15,xGhato40k,332,BRONZE,17,8,0.680000,6.640000,6.360000,10.040000,NONE,...,78.680000,16141.480000,1,8.600000,0,301.280000,101252.960000,696953,23.479333,15.296000
16,Shinnoke,143,BRONZE,13,12,0.520000,9.120000,8.600000,18.960000,SUPPORT,...,37.520000,12723.760000,2,18.640000,0,442.680000,82693.920000,637542,27.208000,16.978667
17,Ry rakku,72,BRONZE,14,11,0.560000,4.520000,7.880000,11.480000,SUPPORT,...,75.800000,9993.280000,1,36.640000,0,526.360000,86120.360000,627636,29.511333,16.107333
18,xXCULdeZACXx,296,BRONZE,13,12,0.520000,5.200000,7.440000,7.800000,NONE,...,36.600000,13657.280000,0,14.320000,0,367.280000,110664.880000,741373,23.609333,16.732667
19,Crøwnie cløwn,68,BRONZE,16,9,0.640000,7.040000,4.800000,8.160000,SUPPORT,...,91.800000,10189.600000,2,25.720000,0,517.040000,92740.920000,468807,25.504667,15.140667

In [ ]:
# Display the last 20 records
data[-20:]

,summonerName,summonerLevel,rank,wins,losses,winRate,kills,deaths,assists,prefLane,...,minionsKilled,goldEarned,turretTakedowns,visionScore,dragonKills,longestTimeSpentLiving,totalDamageDealt,totalDamageTaken,gameDuration,gameStart
2265,PufarinaTerorist,498,SILVER,10,15,0.40,7.84,9.72,14.84,SUPPORT,...,58.52,12212.56,1,20.28,0,444.88,97974.36,653298,27.714667,18.370667
2266,Ponus,535,SILVER,15,10,0.60,7.80,8.36,9.80,MIDDLE,...,148.52,13216.68,2,16.92,0,486.52,162535.40,658910,30.866667,16.359333
2267,5 VS 1 pls,757,SILVER,12,13,0.48,8.04,8.56,10.16,ADC,...,156.72,14820.00,2,45.44,0,609.52,181859.20,715518,35.542667,16.342667
2268,Koroky,182,SILVER,15,10,0.60,7.48,6.88,7.76,ADC,...,106.48,11195.20,2,18.84,0,532.52,116400.72,655995,29.422000,14.599333
2269,Freddy North,429,SILVER,8,17,0.32,6.76,7.32,4.96,JUNGLE,...,32.60,11717.68,1,17.48,1,596.32,225696.32,815221,28.704667,18.649333
2270,Bengaljungleking,59,SILVER,8,17,0.32,7.24,10.72,8.48,ADC,...,149.16,12261.52,1,18.64,0,418.32,135872.48,929812,27.540667,18.729333
2271,Ànky,46,SILVER,18,7,0.72,11.72,6.32,9.56,ADC,...,171.24,14314.08,3,18.16,0,468.00,175145.72,618103,27.294000,15.704000
2272,suezor,382,SILVER,10,15,0.40,5.96,7.12,7.64,ADC,...,156.48,11929.16,2,19.76,0,535.40,138847.08,565766,28.566000,16.641333
2273,T4rtine2Sp3rme,385,SILVER,13,12,0.52,6.44,6.16,7.04,TOP,...,150.24,12184.36,2,28.60,0,584.24,132811.88,756501,30.303333,18.066667
2274,WiShEdIwAsMe,291,SILVER,10,15,0.40,5.28,7.88,9.04,JUNGLE,...,64.04,10536.80,1,29.96,0,472.96,132147.40,729420,28.498667,15.906000
2275,RBW Sneaky,249,SILVER,9,16,0.36,8.44,7.28,8.32,ADC,...,91.56,13575.56,1,11.24,0,408.04,93493.16,652354,24.123333,13.793333
2276,karimbob1,275,SILVER,8,17,0.32,6.52,7.92,6.68,JUNGLE,...,31.64,13515.08,0,17.72,0,343.44,125787.40,908414,25.190000,19.601333
2277,SAidan2,299,SILVER,13,12,0.52,6.32,5.72,5.88,ADC,...,163.88,11911.64,2,21.48,0,535.96,161946.60,582880,28.711333,16.734667
2278,Lerni,385,SILVER,14,11,0.56,6.88,8.76,12.84,SUPPORT,...,104.68,12347.68,2,39.56,0,538.12,99039.08,747853,32.621333,19.408000
2279,Shue,244,SILVER,10,15,0.40,7.16,6.16,7.04,ADC,...,132.48,13839.08,1,11.12,0,498.76,120871.04,572329,26.500000,15.902667
2280,DarkLady Lilith,516,SILVER,12,13,0.48,7.36,6.04,12.92,MIDDLE,...,138.36,12483.88,2,36.24,0,634.64,124161.88,540583,31.024000,15.213333
2281,IceTeaTs,241,SILVER,9,16,0.36,7.40,7.96,11.68,NONE,...,98.52,12285.04,1,9.44,0,346.32,97369.36,521546,22.320000,14.589333
2282,EasyEichel,312,SILVER,15,10,0.60,9.20,8.04,8.36,MIDDLE,...,87.72,13425.88,1,14.48,0,374.04,196456.52,809734,28.762667,15.082667
2283,popomu elleyin,520,SILVER,9,16,0.36,6.36,7.76,7.92,NONE,...,103.88,14513.68,1,24.40,0,404.08,143844.24,826660,29.032000,14.207333
2284,yELFD,242,SILVER,14,11,0.56,5.16,6.28,7.76,TOP,...,145.08,11735.84,2,13.60,0,523.24,138998.40,699002,28.106667,11.912000

In [ ]:
# Changing column name
data.rename(columns={'summonerName': 'In Game Name'}, inplace = True)
data

,In Game Name,summonerLevel,rank,wins,losses,winRate,kills,deaths,assists,prefLane,...,minionsKilled,goldEarned,turretTakedowns,visionScore,dragonKills,longestTimeSpentLiving,totalDamageDealt,totalDamageTaken,gameDuration,gameStart
0,RoséPosié,712,BRONZE,13,12,0.52,3.20,6.72,15.36,SUPPORT,...,50.32,8982.20,1,45.56,0,506.96,48651.12,544240,28.566667,7.216000
1,Xest,199,BRONZE,12,13,0.48,8.36,5.72,14.44,SUPPORT,...,47.40,11866.56,0,29.96,0,494.00,78143.68,441284,24.580667,16.400000
2,SilverHawk0,340,BRONZE,11,14,0.44,8.20,9.00,7.88,TOP,...,186.16,13236.60,1,19.96,0,438.64,150665.56,743065,30.250667,16.724667
3,Res93,61,BRONZE,12,13,0.48,8.60,7.52,8.20,ADC,...,190.00,13367.08,2,25.36,0,558.36,170517.52,594545,30.931333,17.265333
4,B3tterTh4nYo0,124,BRONZE,8,17,0.32,5.24,7.32,8.76,JUNGLE,...,97.76,11655.24,0,21.28,0,563.40,152541.04,652545,29.800000,13.505333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2280,DarkLady Lilith,516,SILVER,12,13,0.48,7.36,6.04,12.92,MIDDLE,...,138.36,12483.88,2,36.24,0,634.64,124161.88,540583,31.024000,15.213333
2281,IceTeaTs,241,SILVER,9,16,0.36,7.40,7.96,11.68,NONE,...,98.52,12285.04,1,9.44,0,346.32,97369.36,521546,22.320000,14.589333
2282,EasyEichel,312,SILVER,15,10,0.60,9.20,8.04,8.36,MIDDLE,...,87.72,13425.88,1,14.48,0,374.04,196456.52,809734,28.762667,15.082667
2283,popomu elleyin,520,SILVER,9,16,0.36,6.36,7.76,7.92,NONE,...,103.88,14513.68,1,24.40,0,404.08,143844.24,826660,29.032000,14.207333
2284,yELFD,242,SILVER,14,11,0.56,5.16,6.28,7.76,TOP,...,145.08,11735.84,2,13.60,0,523.24,138998.40,699002,28.106667,11.912000

In [ ]:
# Create a new dataframe with a player with no turret take downs
noturretdf = pd.DataFrame(data)
noturretdf = data[data['turretTakedowns'] == 0]
noturretdf

,In Game Name,summonerLevel,rank,wins,losses,winRate,kills,deaths,assists,prefLane,...,minionsKilled,goldEarned,turretTakedowns,visionScore,dragonKills,longestTimeSpentLiving,totalDamageDealt,totalDamageTaken,gameDuration,gameStart
1,Xest,199,BRONZE,12,13,0.48,8.36,5.72,14.44,SUPPORT,...,47.40,11866.56,0,29.96,0,494.00,78143.68,441284,24.580667,16.400000
4,B3tterTh4nYo0,124,BRONZE,8,17,0.32,5.24,7.32,8.76,JUNGLE,...,97.76,11655.24,0,21.28,0,563.40,152541.04,652545,29.800000,13.505333
13,Pok1 Feet,323,BRONZE,12,13,0.48,6.92,5.56,5.08,MIDDLE,...,180.48,11631.56,0,17.20,0,608.92,140302.32,558984,27.981333,17.744667
18,xXCULdeZACXx,296,BRONZE,13,12,0.52,5.20,7.44,7.80,NONE,...,36.60,13657.28,0,14.32,0,367.28,110664.88,741373,23.609333,16.732667
62,Valtrau,143,BRONZE,10,15,0.40,3.96,5.16,8.80,TOP,...,102.20,10603.48,0,19.96,0,619.76,87116.08,724038,28.466667,16.556667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2167,PittBulll,214,SILVER,10,15,0.40,4.20,6.00,6.56,NONE,...,53.76,12480.32,0,13.56,0,424.24,91647.00,695780,24.504000,14.242000
2170,CheckmyQ,33,SILVER,14,11,0.56,9.20,6.48,10.96,JUNGLE,...,45.36,15060.80,0,19.92,1,708.76,324115.16,1345198,33.943333,12.337333
2181,N00BBUTPRO,263,SILVER,11,14,0.44,5.16,6.84,8.40,NONE,...,56.08,15576.48,0,8.60,0,288.80,72666.52,739925,22.288667,15.598000
2215,VaChoRen,92,SILVER,16,9,0.64,6.72,6.16,6.96,JUNGLE,...,20.12,12005.08,0,17.48,1,498.48,246819.12,801704,29.620000,14.723333
2276,karimbob1,275,SILVER,8,17,0.32,6.52,7.92,6.68,JUNGLE,...,31.64,13515.08,0,17.72,0,343.44,125787.40,908414,25.190000,19.601333

In [ ]:
# Create a new dataframe that is level 900 above
leveldf = pd.DataFrame(data)
leveldf = data[data['summonerLevel'] >= 900].copy()
leveldf

,In Game Name,summonerLevel,rank,wins,losses,winRate,kills,deaths,assists,prefLane,...,minionsKilled,goldEarned,turretTakedowns,visionScore,dragonKills,longestTimeSpentLiving,totalDamageDealt,totalDamageTaken,gameDuration,gameStart
196,Adnachiel,1010,BRONZE,15,10,0.60,8.48,7.96,9.56,TOP,...,137.04,13179.88,2,14.88,0,521.68,169723.20,750188,28.729333,15.058000
291,Forbenn,1445,DIAMOND,15,10,0.60,1.56,4.72,15.44,SUPPORT,...,32.92,7883.00,1,64.36,0,570.04,26249.32,422255,25.804667,13.373333
297,why so obsessed,1199,DIAMOND,16,9,0.64,1.96,4.56,15.32,SUPPORT,...,17.52,8200.24,3,52.20,0,499.40,19701.32,382005,27.075333,9.632667
300,Squelerex,941,DIAMOND,14,11,0.56,5.28,5.24,5.84,TOP,...,211.40,12620.20,2,15.88,0,748.56,170098.24,767398,30.466000,15.331333
308,jhgkjhggkjhkjhg,1466,DIAMOND,12,13,0.48,5.56,6.84,7.48,MIDDLE,...,181.44,11382.52,2,16.04,0,454.92,138646.20,496890,25.456000,19.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877,ethans01,1197,PLATINUM,8,17,0.32,5.76,7.32,5.32,NONE,...,92.92,12655.52,0,9.60,0,319.76,119285.80,644891,22.335333,16.505333
1886,TSW B4lrog,1018,PLATINUM,14,11,0.56,4.96,6.96,12.00,SUPPORT,...,103.92,11301.88,1,43.92,0,601.84,100921.64,663362,30.834667,16.074000
2016,Staphany San,1100,SILVER,10,15,0.40,10.92,7.36,8.72,ADC,...,143.32,13040.40,2,32.40,0,504.84,145696.80,611282,29.553333,14.226667
2124,Shineo,914,SILVER,11,14,0.44,5.12,5.56,7.72,NONE,...,25.20,12994.68,0,28.52,0,320.96,55026.36,635828,20.912000,18.013333
2187,OBK Chi3us3 Love,1547,SILVER,13,12,0.52,3.52,8.24,14.24,SUPPORT,...,59.52,10500.88,1,65.44,0,487.76,71141.00,570824,29.132667,14.286000

In [ ]:
# Making another dataframe showing "kills" and the Account info only
killdf = pd.DataFrame(data, columns=['In Game Name', 'kills', 'rank', 'summonerLevel'])
killdf

         In Game Name  kills    rank  summonerLevel
0           RoséPosié   3.20  BRONZE            712
1                Xest   8.36  BRONZE            199
2         SilverHawk0   8.20  BRONZE            340
3               Res93   8.60  BRONZE             61
4       B3tterTh4nYo0   5.24  BRONZE            124
...               ...    ...     ...            ...
2280  DarkLady Lilith   7.36  SILVER            516
2281         IceTeaTs   7.40  SILVER            241
2282       EasyEichel   9.20  SILVER            312
2283   popomu elleyin   6.36  SILVER            520
2284            yELFD   5.16  SILVER            242

[2285 rows x 4 columns]

In [ ]:
# getting the mean of kills and deaths of each player
mean_killndeath = np.mean(data['kills']), np.mean(data['deaths'])
mean_killndeath

(6.736992219790907, 6.602601507415512)

In [ ]:
# getting the median of wins and summonerLevel of each player
median_killndeath = np.median(data['wins']), np.median(data['summonerLevel'])
median_killndeath

(13.0, 354.0)

In [ ]:
# Getting the Min and Max goldEarned of each player
max_goldearned = max(data['goldEarned'])
min_goldearned = min(data['goldEarned'])

print("Max gold earned:",max_goldearned)
print("Min gold earned:",min_goldearned)

Max gold earned: 17637.84
Min gold earned: 3464.4

In [ ]:
#15 Use numpy to get the standard deviation of the totalDamageDealt.
stdev_totalDamageDealt = np.std(data['totalDamageDealt'])
stdev_totalDamageDealt

51427.04905084079